version: "3"
services:
  
  graphdb:
    image: graph-db:9.7.0
    restart: always
    hostname: graphdb
    ports:
      - 7200:7200
    volumes:
      - graphdb-data:/opt/graphdb/home

#note that if you have not set-up specific security on graphdb,
#you do not need to set the environment
#We recommend using a .env file in this folder to set your environment
  cde-box-daemon: 
    image: markw/cde-box-daemon:latest
    container_name: cde-box-daemon
    environment:
      GraphDB_User: ${GraphDB_User}
      GraphDB_Pass: ${GraphDB_Pass}
    depends_on:
      - yarrrml_transform
      - rdfizer
      - graphdb
    ports:
      - 4567:4567
    volumes:
        - ./data:/data
        - ./config:/config
        
        
  yarrrml_transform: 
    image: markw/yarrrml-parser-ejp:latest
    container_name: yarrrml_transform
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
  
  
  rdfizer: 
    image: markw/sdmrdfizer_ejp:0.1.0
    container_name: rdfizer
    ports:
      - "4000:4000"
    volumes:
      - ./data:/data
      - ./config:/config

    
volumes:
  graphdb-data:
    external: true

